application: dar-static
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /jsmath/.*
  script: zip/serve.py

- url: /colorpicker/.*
  script: zip/serve.py

- url: /projects/lljvm/doc/.*
  script: zip/serve.py

- url: /xrds
  static_files: xrds.xml
  upload: xrds.xml
  mime_type: application/xrds+xml
